/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT UPDATE IT DIRECTLY
 */

import './assets/styles.scss'
import Vue from 'vue'
import { setDefaults } from './utils/defaults'
import SButton from './components/SButton'
import SButtonGroup from './components/SButtonGroup'
import SCallout from './components/SCallout'
import SCard from './components/SCard'
import SCardContainer from './components/SCardContainer'
import SCheckbox from './components/SCheckbox'
import SChip from './components/SChip'
import SChipGroup from './components/SChipGroup'
import SCollapse from './components/SCollapse'
import SContainer from './components/SContainer'
import SContainerColumn from './components/SContainerColumn'
import SContainerRow from './components/SContainerRow'
import SFileInput from './components/SFileInput'
import SFormField from './components/SFormField'
import SFormValidation from './components/SFormValidation'
import SHeading from './components/SHeading'
import SHero from './components/SHero'
import SIcon from './components/SIcon'
import SInput from './components/SInput'
import SLabel from './components/SLabel'
import SLazyImage from './components/SLazyImage'
import SLink from './components/SLink'
import SLogo from './components/SLogo'
import SProgressBar from './components/SProgressBar'
import SRadio from './components/SRadio'
import SSelect from './components/SSelect'
import SSpinner from './components/SSpinner'
import SSwitch from './components/SSwitch'
import STable from './components/STable'
import STableCell from './components/STableCell'
import STableRow from './components/STableRow'
import STextarea from './components/STextarea'
import SToast from './components/SToast'

const Schedio = {
  install (Vue, options = {}) {
    setDefaults(options)

    Vue.use(SButton)
    Vue.use(SButtonGroup)
    Vue.use(SCallout)
    Vue.use(SCard)
    Vue.use(SCardContainer)
    Vue.use(SCheckbox)
    Vue.use(SChip)
    Vue.use(SChipGroup)
    Vue.use(SCollapse)
    Vue.use(SContainer)
    Vue.use(SContainerColumn)
    Vue.use(SContainerRow)
    Vue.use(SFileInput)
    Vue.use(SFormField)
    Vue.use(SFormValidation)
    Vue.use(SHeading)
    Vue.use(SHero)
    Vue.use(SIcon)
    Vue.use(SInput)
    Vue.use(SLabel)
    Vue.use(SLazyImage)
    Vue.use(SLink)
    Vue.use(SLogo)
    Vue.use(SProgressBar)
    Vue.use(SRadio)
    Vue.use(SSelect)
    Vue.use(SSpinner)
    Vue.use(SSwitch)
    Vue.use(STable)
    Vue.use(STableCell)
    Vue.use(STableRow)
    Vue.use(STextarea)
    Vue.use(SToast)
  },
}

if (typeof window !== 'undefined' && window.Vue) Vue.use(Schedio)

export default Schedio

export { SButton } from './components/SButton'
export { SButtonGroup } from './components/SButtonGroup'
export { SCallout } from './components/SCallout'
export { SCard } from './components/SCard'
export { SCardContainer } from './components/SCardContainer'
export { SCheckbox } from './components/SCheckbox'
export { SChip } from './components/SChip'
export { SChipGroup } from './components/SChipGroup'
export { SCollapse } from './components/SCollapse'
export { SContainer } from './components/SContainer'
export { SContainerColumn } from './components/SContainerColumn'
export { SContainerRow } from './components/SContainerRow'
export { SFileInput } from './components/SFileInput'
export { SFormField } from './components/SFormField'
export { SFormValidation } from './components/SFormValidation'
export { SHeading } from './components/SHeading'
export { SHero } from './components/SHero'
export { SIcon } from './components/SIcon'
export { SInput } from './components/SInput'
export { SLabel } from './components/SLabel'
export { SLazyImage } from './components/SLazyImage'
export { SLink } from './components/SLink'
export { SLogo } from './components/SLogo'
export { SProgressBar } from './components/SProgressBar'
export { SRadio } from './components/SRadio'
export { SSelect } from './components/SSelect'
export { SSpinner } from './components/SSpinner'
export { SSwitch } from './components/SSwitch'
export { STable } from './components/STable'
export { STableCell } from './components/STableCell'
export { STableRow } from './components/STableRow'
export { STextarea } from './components/STextarea'
export { SToast } from './components/SToast'
